### ISSUE TITLE
Snapshot information inaccurate

### ISSUE THREAD

**Issue by bobvandevijver** [zenstruck/messenger-monitor-bundle#83] opened 2024-04-12 08:19 UTC
I do not know why, but the snapshot information seems to be a bit random compared with the messages that have been recorded in the history.

![image](https://github.com/zenstruck/messenger-monitor-bundle/assets/1835343/1c860b64-44b2-414c-80a2-a96bae36f865)

**Comment by kbond** [comment] 2024-04-12 14:26
Hmm, yeah, that's not good. Did you recently update this package?

**Comment by bobvandevijver** [comment] 2024-04-12 14:53
Well, not necessarily updated: this is a fresh installation of v0.2.0 that I deployed last Wednesday evening.

**Comment by kbond** [comment] 2024-04-12 15:04
Is it easy for you to see if 0.1.0 has the same problem?

**Comment by bobvandevijver** [comment] 2024-04-12 15:29
I just downgraded on our staging machine, doesn't seem to change anything unfortunately

**Comment by kbond** [comment] 2024-04-12 15:34
Thanks for checking. Despite not being stable, this bundle does have quite a few early adopters so hard to imagine no one else reporting this. It's super clear in your screenshot the snapshot is wrong.

Do you see the same thing in the command line?

Is the "last 24 hours" snapshot on the dashboard wrong as well?

What DB are you using?

**Comment by bobvandevijver** [comment] 2024-04-12 15:47
I completely agree, but I must say I dismissed the stats when implementing it first due to being on dev with not that much messages. I see the same in the command line, and all snapshots are wrong.

But, it looks like I found the culprit: I am using MariaDB, and it seems that removing the group by id statement in from the ORMStorage solves everything. You added them here: https://github.com/zenstruck/messenger-monitor-bundle/commit/a4fc554d0e9a793f404e5f18767f7f4d06258d6d.

**Comment by bobvandevijver** [comment] 2024-04-12 15:51
On MySQL 8 with another project I see the same issue by the way, removing the group by resolves the issue there as well.

**Comment by kbond** [comment] 2024-04-12 16:23
Ok, glad we have found the cause!

It's clear that when we have better test coverage for this bundle, we'll need to have the CI test on several different database platforms (we've had issues like this before).

For the fix, do you think we can we simply remove the groupBy statements across the board, or do we need to make it conditional on the db platform. I'm not sure why I added groupby to begin with - [this](https://www.doctrine-project.org/projects/doctrine-orm/en/3.1/cookbook/aggregate-fields.html#using-dql) clearly shows it isn't needed for this type of query.

I'm guessing it's something to do with zenstruck/collection (and I may have fixed this in a recent version).

**Comment by bobvandevijver** [comment] 2024-04-13 09:24
From my understanding, grouping on the id property does not make sense if you are not joining in such a way that you would end up with multiple rows for the same record. As this bundle only utilises a single column and simple where statements, I believe it should be safe to remove.

**Comment by kbond** [comment] 2024-04-14 16:22
Fixed via #84.

**Closed as completed by kbond** 2024-04-14 16:22 UTC
